create table if not exists disaster_data (
  begin_yearmonth integer,
  begin_day integer,
  begin_time integer,
  end_yearmonth integer,
  end_day integer,
  end_time integer,
  episode_id integer,
  event_id integer,
  state varchar(200) ,
  state_fips integer ,
  year integer ,
  month_name varchar(30) ,
  event_type varchar(200) ,
  cz_type varchar(1) ,
  cz_fips integer ,
  cz_name varchar(200) ,
  wfo varchar(100) ,
  begin_date_time timestamp ,
  cz_timezone varchar(50) ,
  end_date_time timestamp ,
  injuries_direct integer ,
  injuries_indirect integer ,
  deaths_direct integer ,
  deaths_indirect integer ,
  damage_property varchar(100) ,
  damage_crops varchar(100) ,
  source varchar(200) ,
  magnitude integer ,
  magnitude_type varchar(100) ,
  flood_cause varchar(200) ,
  category varchar(100) ,
  tor_f_scale varchar(50) ,
  tor_length float ,
  tor_width integer ,
  tor_other_wfo varchar(500) ,
  tor_other_cz_state varchar(500) ,
  tor_other_cz_fips varchar(200) ,
  tor_other_cz_name varchar(200) ,
  begin_range integer ,
  begin_azimuth varchar(100) ,
  begin_location varchar(200) ,
  end_range integer ,
  end_azimuth varchar(50) ,
  end_location varchar(200) ,
  begin_lat float ,
  begin_lon float ,
  end_lat float ,
  end_lon float ,
  episode_narrative text ,
  event_narrative text ,
  data_source varchar(200) ,
  __date_loaded timestamp default now(),
  __row_hash varchar(1000),
  __filename varchar(100) default null
);